services:
  api-service:
    build: .
    container_name: api-service
    ports:
      - "8000:8000"
    restart: always

  backend-service:
    image: nginx:latest
    container_name: backend-service
    ports:
      - "8080:80"
    restart: always